dist: bionic

language: node_js
node_js:
  - 12
  - 10

sudo: false

addons:
  postgresql: 9.6

services:
  - mysql
  - postgresql
  - mongodb
  - redis-server

before_script:
  - mysql -u travis -e "drop table if exists travis.test"
  - psql -U postgres -c 'create database travis_ci_test;'

script: lerna run test
