dist: bionic

language: node_js
node_js:
  - 12
  - 10

sudo: false

services:
  - mysql
  - postgresql
  - mongodb
  - redis-server

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: lerna run test
