version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: cormo_test
      MYSQL_USER: cormo_test
      MYSQL_PASSWORD: cormo_test
    ports:
      - 21860:3306

  mongo:
    image: mongo:3.6-xenial
    ports:
      - 21861:27017

  postgres:
    image: croquiscom/postgis-pgvector:16-3.5-0.7.3
    environment:
      POSTGRES_DB: cormo_test
      POSTGRES_USER: cormo_test
      POSTGRES_PASSWORD: cormo_test
    ports:
      - 21862:5432

  redis:
    image: redis:4-alpine
    ports:
      - 21863:6379
