// Generated by CoffeeScript 1.6.2
(function() {
  var CommandConsole, Connection, Fiber, Future, Model, addHistory, addMultilineHandler, coffee, commander, fs, path, prettyErrorMessage, repl, vm;

  coffee = require('coffee-script');

  commander = require('commander');

  Fiber = require('fibers');

  Future = require('fibers/future');

  path = require('path');

  repl = require('repl');

  vm = require('vm');

  fs = require('fs');

  Connection = require('../connection');

  Model = require('../model');

  prettyErrorMessage = coffee.helpers.prettyErrorMessage || function(e) {
    return e;
  };

  addMultilineHandler = function(repl) {
    var inputStream, multiline, nodeLineListener, outputStream, rli;

    rli = repl.rli, inputStream = repl.inputStream, outputStream = repl.outputStream;
    multiline = {
      enabled: false,
      initialPrompt: repl.prompt.replace(/^[^> ]*/, function(x) {
        return x.replace(/./g, '-');
      }),
      prompt: repl.prompt.replace(/^[^> ]*>?/, function(x) {
        return x.replace(/./g, '.');
      }),
      buffer: ''
    };
    nodeLineListener = rli.listeners('line')[0];
    rli.removeListener('line', nodeLineListener);
    rli.on('line', function(cmd) {
      if (multiline.enabled) {
        multiline.buffer += "" + cmd + "\n";
        rli.setPrompt(multiline.prompt);
        rli.prompt(true);
      } else {
        nodeLineListener(cmd);
      }
    });
    return inputStream.on('keypress', function(char, key) {
      if (!(key && key.ctrl && !key.meta && !key.shift && key.name === 'v')) {
        return;
      }
      if (multiline.enabled) {
        if (!multiline.buffer.match(/\n/)) {
          multiline.enabled = !multiline.enabled;
          rli.setPrompt(repl.prompt);
          rli.prompt(true);
          return;
        }
        if ((rli.line != null) && !rli.line.match(/^\s*$/)) {
          return;
        }
        multiline.enabled = !multiline.enabled;
        rli.line = '';
        rli.cursor = 0;
        rli.output.cursorTo(0);
        rli.output.clearLine(1);
        multiline.buffer = multiline.buffer.replace(/\n/g, '\uFF00');
        rli.emit('line', multiline.buffer);
        multiline.buffer = '';
      } else {
        multiline.enabled = !multiline.enabled;
        rli.setPrompt(multiline.initialPrompt);
        rli.prompt(true);
      }
    });
  };

  addHistory = function(repl, filename, maxSize) {
    var buffer, fd, lastLine, readFd, size, stat;

    lastLine = null;
    try {
      stat = fs.statSync(filename);
      size = Math.min(maxSize, stat.size);
      readFd = fs.openSync(filename, 'r');
      buffer = new Buffer(size);
      fs.readSync(readFd, buffer, 0, size, stat.size - size);
      repl.rli.history = buffer.toString().split('\n').reverse();
      if (stat.size > maxSize) {
        repl.rli.history.pop();
      }
      if (repl.rli.history[0] === '') {
        repl.rli.history.shift();
      }
      repl.rli.historyIndex = -1;
      lastLine = repl.rli.history[0];
    } catch (_error) {}
    fd = fs.openSync(filename, 'a');
    repl.rli.addListener('line', function(code) {
      if (code && code.length && code !== '.history' && lastLine !== code) {
        fs.write(fd, "" + code + "\n");
        return lastLine = code;
      }
    });
    repl.rli.on('exit', function() {
      return fs.close(fd);
    });
    return repl.commands['.history'] = {
      help: 'Show command history',
      action: function() {
        repl.outputStream.write("" + (repl.rli.history.slice(0).reverse().join('\n')) + "\n");
        return repl.displayPrompt();
      }
    };
  };

  CommandConsole = (function() {
    function CommandConsole(argv) {
      var cwd, load, loads, program, _i, _len;

      loads = [];
      this.program = program = new commander.Command('cormo');
      program.usage('console [options]').option('-l, --load <path>', 'load specified module').on('load', function(path) {
        return loads.push(path);
      });
      if (argv.indexOf('--help') >= 0 || argv.indexOf('-h') >= 0) {
        program.help();
      }
      program.parse(argv);
      try {
        cwd = process.cwd();
        for (_i = 0, _len = loads.length; _i < _len; _i++) {
          load = loads[_i];
          console.log("Loading module '" + load + "'...");
          require(path.resolve(cwd, load));
        }
      } catch (_error) {}
    }

    CommandConsole.prototype.run = function() {
      return this.runCoffee();
    };

    CommandConsole.prototype.runCoffee = function() {
      var historyFile;

      repl = repl.start({
        prompt: 'cormo> ',
        "eval": function(cmd, context, filename, callback) {
          return Fiber(function() {
            var assign_to, e, future, js, result, use_future;

            cmd = cmd.replace(/\uFF00/g, '\n');
            cmd = cmd.replace(/^\(([\s\S]*)\n\)$/m, '$1');
            if (!cmd) {
              return callback(null);
            }
            use_future = /[, ]\$$/.test(cmd);
            if (use_future) {
              future = new Future();
              context.$ = future.resolver();
            }
            if (/^\s*([a-zA-Z_$][0-9a-zA-Z_$]*)\s=/.test(cmd)) {
              assign_to = RegExp.$1;
            }
            try {
              js = coffee.compile(cmd, {
                filename: filename,
                bare: true
              });
              result = vm.runInContext(js, context, filename);
              if (use_future) {
                result = future.wait();
                if (assign_to) {
                  context[assign_to] = result;
                }
                delete context.$;
              }
            } catch (_error) {
              e = _error;
              return callback(prettyErrorMessage(e, filename, cmd, true));
            }
            return callback(null, result);
          }).run();
        }
      });
      repl.on('exit', function() {
        return process.exit(0);
      });
      addMultilineHandler(repl);
      if (process.env.HOME) {
        historyFile = path.join(process.env.HOME, '.cormo_history');
      }
      if (historyFile) {
        addHistory(repl, historyFile, 10240);
      }
      return this._setupContext(repl.context);
    };

    CommandConsole.prototype._setupContext = function(context) {
      var connection, model, modelClass, _ref, _results;

      context.Connection = Connection;
      context.Model = Model;
      context.connection = connection = Connection.defaultConnection;
      if (connection) {
        _ref = connection.models;
        _results = [];
        for (model in _ref) {
          modelClass = _ref[model];
          _results.push(context[model] = modelClass);
        }
        return _results;
      }
    };

    return CommandConsole;

  })();

  module.exports = CommandConsole;

}).call(this);
