// Generated by CoffeeScript 1.6.2
(function() {
  var CommandConsole, coffee, prettyErrorMessage, repl, vm;

  coffee = require('coffee-script');

  repl = require('repl');

  vm = require('vm');

  prettyErrorMessage = coffee.helpers.prettyErrorMessage || function(e) {
    return e;
  };

  CommandConsole = (function() {
    function CommandConsole(argv) {}

    CommandConsole.prototype.run = function() {
      return this.runCoffee();
    };

    CommandConsole.prototype.runCoffee = function() {
      return repl.start({
        prompt: 'cormo> ',
        "eval": function(cmd, context, filename, callback) {
          var e, js, result;

          if (cmd[0] === '(' && cmd[cmd.length - 1] === ')' && !cmd.substr(1, cmd.length - 2).trim()) {
            return callback(null);
          }
          try {
            js = coffee.compile(cmd, {
              filename: filename,
              bare: true
            });
            result = vm.runInContext(js, context, filename);
          } catch (_error) {
            e = _error;
            return callback(prettyErrorMessage(e, filename, cmd, true));
          }
          return callback(null, result);
        }
      });
    };

    return CommandConsole;

  })();

  module.exports = CommandConsole;

}).call(this);
