// Generated by CoffeeScript 1.10.0
(function() {
  var CommandRemoteConsole, net;

  net = require('net');

  CommandRemoteConsole = (function() {
    function CommandRemoteConsole(argv) {
      this.argv = argv.slice(3);
    }

    CommandRemoteConsole.prototype.run = function() {
      var socket;
      if (this.argv.length === 0) {
        this.help();
        return;
      }
      socket = net.connect.apply(net, this.argv);
      process.stdin.pipe(socket);
      socket.pipe(process.stdout);
      socket.on('connect', function() {
        process.stdin.setRawMode(true);
      });
      socket.once('close', function() {
        process.stdin.emit('end');
      });
      process.stdin.on('end', function() {
        process.stdin.setRawMode(false);
        socket.end();
        console.log();
      });
    };

    CommandRemoteConsole.prototype.help = function() {
      console.log('Usage: cormo remote-console port [host]');
      console.log('Usage: cormo remote-console path');
    };

    return CommandRemoteConsole;

  })();

  module.exports = CommandRemoteConsole;

}).call(this);
