// Generated by CoffeeScript 1.3.3

/*
# Base class for adapters
*/


(function() {
  var AdapterBase;

  AdapterBase = (function() {

    function AdapterBase() {}

    /*
      # Wraps adapter specific errors
      # @param {String} msg CORMO's error message
      # @param {Error} cause adapter specific error object
    */


    AdapterBase.wrapError = function(msg, cause) {
      var error;
      error = new Error(msg);
      error.cause = cause;
      return error;
    };

    return AdapterBase;

  })();

  module.exports = AdapterBase;

}).call(this);
