// Generated by CoffeeScript 1.3.3
(function() {
  var mysql, _wrapError;

  try {
    mysql = require('mysql');
  } catch (error) {
    console.log('Install mysql module to use this adapter');
    process.exit(1);
  }

  _wrapError = function(msg, cause) {
    error = new Error(msg);
    error.cause = cause;
    return error;
  };

  /*
  # Initialize MySQL adapter
  # @param {Connection} connection
  # @param {Object} settings
  # @param {String} [settings.host]
  # @param {Number} [settings.port]
  # @param {String} [settings.user]
  # @param {String} [settings.password]
  # @param {String} settings.database
  # @param {Function} callback
  # @param {Error} callback.error
  # @param {MySQLAdapter} callback.adapter
  */


  module.exports = function(connection, settings, callback) {
    var client;
    client = mysql.createConnection({
      host: settings.host,
      port: settings.port,
      user: settings.user,
      password: settings.password
    });
    return client.connect(function(error) {
      if (error) {
        return callback(_wrapError('failed to connect', error));
      }
      return client.query("USE `" + settings.database + "`", function(error) {
        var msg;
        if (!error) {
          return callback(null);
        }
        if (error.code === 'ER_BAD_DB_ERROR') {
          return client.query("CREATE DATABASE `" + settings.database + "`", function(error) {
            if (error) {
              return callback(_wrapError('unknown error', error));
            }
            return callback(null);
          });
        } else {
          msg = error.code === 'ER_DBACCESS_DENIED_ERROR' ? "no access right to the database '" + settings.database + "'" : 'unknown error';
          return callback(_wrapError(msg, error));
        }
      });
    });
  };

}).call(this);
