// Generated by CoffeeScript 1.7.1
(function() {
  var AdapterBase, SQLAdapterBase, types,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AdapterBase = require('./base');

  types = require('../types');

  SQLAdapterBase = (function(_super) {
    __extends(SQLAdapterBase, _super);

    function SQLAdapterBase() {
      return SQLAdapterBase.__super__.constructor.apply(this, arguments);
    }

    SQLAdapterBase.prototype._param_place_holder = function(pos) {
      return '?';
    };

    SQLAdapterBase.prototype._contains_op = 'LIKE';

    SQLAdapterBase.prototype._buildWhereSingle = function(property, key, value, params) {
      var keys, op, property_type, sub_key, values;
      if (key !== 'id' && (property == null)) {
        throw new Error("unknown column '" + key + "'");
      }
      property_type = property != null ? property.type : void 0;
      if (property && !property_type) {
        key = this._buildGroupExpr(property);
      }
      op = '=';
      if (Array.isArray(value)) {
        values = value.map((function(_this) {
          return function(value) {
            params.push(value);
            return _this._param_place_holder(params.length);
          };
        })(this));
        return "" + (key.replace('.', '_')) + " IN (" + (values.join(',')) + ")";
      } else if (typeof value === 'object' && (keys = Object.keys(value)).length === 1) {
        sub_key = keys[0];
        switch (sub_key) {
          case '$not':
            if (value[sub_key] === null) {
              return "NOT " + (key.replace('.', '_')) + " IS NULL";
            } else {
              return "(NOT (" + (this._buildWhereSingle(property, key, value[sub_key], params)) + ") OR " + (key.replace('.', '_')) + " IS NULL)";
            }
            break;
          case '$in':
            values = value[sub_key];
            values = values.map((function(_this) {
              return function(value) {
                params.push(value);
                return _this._param_place_holder(params.length);
              };
            })(this));
            return "" + (key.replace('.', '_')) + " IN (" + (values.join(',')) + ")";
          case '$gt':
            op = '>';
            value = value[sub_key];
            break;
          case '$lt':
            op = '<';
            value = value[sub_key];
            break;
          case '$gte':
            op = '>=';
            value = value[sub_key];
            break;
          case '$lte':
            op = '<=';
            value = value[sub_key];
            break;
          case '$contains':
            op = ' ' + this._contains_op + ' ';
            value = '%' + value[sub_key] + '%';
            break;
          default:
            throw new Error("unknown operator '" + sub_key + "'");
        }
      }
      if (property_type === types.Date) {
        value = new Date(value);
      }
      params.push(value);
      return key.replace('.', '_') + op + this._param_place_holder(params.length);
    };

    SQLAdapterBase.prototype._buildWhere = function(schema, conditions, params, conjunction) {
      var key, keys, subs;
      if (conjunction == null) {
        conjunction = 'AND';
      }
      if (Array.isArray(conditions)) {
        subs = conditions.map((function(_this) {
          return function(condition) {
            return _this._buildWhere(schema, condition, params);
          };
        })(this));
      } else if (typeof conditions === 'object') {
        keys = Object.keys(conditions);
        if (keys.length === 0) {
          return '';
        }
        if (keys.length === 1) {
          key = keys[0];
          if (key.substr(0, 1) === '$') {
            switch (key) {
              case '$and':
                return this._buildWhere(schema, conditions[key], params, 'AND');
              case '$or':
                return this._buildWhere(schema, conditions[key], params, 'OR');
            }
          } else {
            return this._buildWhereSingle(schema[key], key, conditions[key], params);
          }
        } else {
          subs = keys.map((function(_this) {
            return function(key) {
              return _this._buildWhereSingle(schema[key], key, conditions[key], params);
            };
          })(this));
        }
      } else {
        throw new Error("'" + (JSON.stringify(conditions)) + "' is not an object");
      }
      if (subs.length === 0) {
        return '';
      } else if (subs.length === 1) {
        return subs[0];
      } else {
        return '(' + subs.join(' ' + conjunction + ' ') + ')';
      }
    };

    SQLAdapterBase.prototype._buildGroupExpr = function(group_expr) {
      var op, sub_expr;
      op = Object.keys(group_expr)[0];
      if (op === '$sum') {
        sub_expr = group_expr[op];
        if (sub_expr === 1) {
          return "COUNT(*)";
        } else if (sub_expr.substr(0, 1) === '$') {
          return "SUM(" + (sub_expr.substr(1)) + ")";
        } else {
          throw new Error("unknown expression '" + (JSON.stringify(op)) + "'");
        }
      } else {
        throw new Error("unknown expression '" + (JSON.stringify(op)) + "'");
      }
    };

    SQLAdapterBase.prototype._buildGroupFields = function(group_by, group_fields) {
      var expr, field, selects;
      selects = [];
      if (group_by) {
        [].push.apply(selects, group_by);
      }
      for (field in group_fields) {
        expr = group_fields[field];
        selects.push("" + (this._buildGroupExpr(expr)) + " as " + field);
      }
      return selects.join(',');
    };

    SQLAdapterBase.prototype._buildSelect = function(model_class, select) {
      var schema;
      if (select) {
        if (select.length > 0) {
          schema = model_class._schema;
          select = select.map(function(column) {
            return schema[column]._dbname;
          });
          return 'id,' + select.join(',');
        } else {
          return 'id';
        }
      } else {
        return '*';
      }
    };

    SQLAdapterBase.prototype._refineRawInstance = function(model, data, selected_columns) {
      var column, id;
      id = this._getModelID(data);
      Object.defineProperty(data, 'id', {
        configurable: false,
        enumerable: true,
        writable: false,
        value: id
      });
      if (this._connection.models[model].eliminate_null) {
        for (column in data) {
          if (data[column] == null) {
            delete data[column];
          }
        }
      }
      return data;
    };

    return SQLAdapterBase;

  })(AdapterBase);

  module.exports = SQLAdapterBase;

}).call(this);
