// Generated by CoffeeScript 2.3.1
var SQLite3Adapter_createAdapter;

SQLite3Adapter_createAdapter = require('./sqlite3');

module.exports = function(connection) {
  var _super_connect, adapter;
  adapter = SQLite3Adapter_createAdapter(connection);
  _super_connect = adapter.connect;
  adapter.connect = function(settings, callback) {
    return _super_connect.call(this, {
      database: ':memory:'
    }, callback);
  };
  return adapter;
};
