"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
// Generated by CoffeeScript 2.3.1
var SQLite3Adapter_createAdapter;
SQLite3Adapter_createAdapter = require('./sqlite3');
module.exports = function (connection) {
    var _super_connect, adapter;
    adapter = SQLite3Adapter_createAdapter(connection);
    _super_connect = adapter.connect;
    adapter.connect = function (settings) {
        return __awaiter(this, void 0, void 0, function* () {
            return (yield _super_connect.call(this, {
                database: ':memory:'
            }));
        });
    };
    return adapter;
};
