// Generated by CoffeeScript 1.7.1
(function() {
  var Command, path;

  path = require('path');

  Command = (function() {
    function Command() {}

    Command.run = function(argv) {
      var CommandClass, command;
      command = argv[2];
      CommandClass = require(path.resolve(__dirname, 'command', command));
      command = new CommandClass(argv);
      return command.run();
    };

    return Command;

  })();

  module.exports = Command;

}).call(this);
