// Generated by CoffeeScript 1.7.1
(function() {
  var Command, path;

  path = require('path');

  Command = (function() {
    function Command() {}

    Command.run = function(argv) {
      var CommandClass, command;
      command = argv[2];
      if (!command) {
        console.log('Usage: cormo <command>');
        return;
      }
      try {
        CommandClass = require(path.resolve(__dirname, 'command', command));
      } catch (_error) {
        console.log("Cannot find a CORMO command " + command);
        return;
      }
      command = new CommandClass(argv);
      return command.run();
    };

    return Command;

  })();

  module.exports = Command;

}).call(this);
