// Generated by CoffeeScript 1.3.3
(function() {
  var DBConnection, DBModel, EventEmitter, _normalizeSchema,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  DBModel = require('./model');

  /*
  # Normalizes a schema
  # (field: String -> field: {type: String})
  */


  _normalizeSchema = function(schema) {
    var field, property;
    for (field in schema) {
      property = schema[field];
      if (typeof property === 'function') {
        schema[field] = {
          type: property
        };
      }
    }
  };

  /*
  # Manages connection to a database
  */


  DBConnection = (function(_super) {

    __extends(DBConnection, _super);

    /*
      # Creates a connection
      # @param {String} adapater_name
      # @param {Object} settings
      # @see MySQLAdapter.createAdapter
      # @see MongoDBAdapter.createAdapter
    */


    function DBConnection(adapter_name, settings) {
      var createAdapter,
        _this = this;
      this.connected = false;
      this.models = {};
      createAdapter = require(__dirname + '/adapters/' + adapter_name);
      createAdapter(this, settings, function(error, adapter) {
        if (error) {
          _this.emit('error', error);
          return;
        }
        _this._adapter = adapter;
        _this.connected = true;
        return _this.emit('connected');
      });
    }

    /*
      # Creates a Model class
      # @param {String} name
      # @param {Object} schema
      # @return {Class}
    */


    DBConnection.prototype.model = function(name, schema) {
      var NewModel;
      _normalizeSchema(schema);
      NewModel = (function(_super1) {

        __extends(NewModel, _super1);

        function NewModel() {
          return NewModel.__super__.constructor.apply(this, arguments);
        }

        return NewModel;

      })(DBModel);
      Object.defineProperty(NewModel, '_connection', {
        value: this
      });
      Object.defineProperty(NewModel, '_name', {
        value: name
      });
      Object.defineProperty(NewModel, '_schema', {
        value: schema
      });
      Object.defineProperty(NewModel, '_associations', {
        value: {}
      });
      this.models[name] = NewModel;
      return NewModel;
    };

    DBConnection.prototype._waitingForConnection = function(object, method, args) {
      if (this.connected) {
        return false;
      }
      this.once('connected', function() {
        return method.apply(object, args);
      });
      return true;
    };

    /*
      # Applies schemas
      # (This makes sense only for SQL adapters)
      # @param {Function} callback
      # @param {Error} callback.error
    */


    DBConnection.prototype.applySchemas = function(callback) {
      if (this._waitingForConnection(this, this.applySchemas, arguments)) {
        return;
      }
      if (this._adapter.applySchemas != null) {
        return this._adapter.applySchemas(callback);
      } else {
        return callback(null);
      }
    };

    return DBConnection;

  })(EventEmitter);

  module.exports = DBConnection;

}).call(this);
