// Generated by CoffeeScript 1.3.3
(function() {
  var DBConnection, EventEmitter,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  EventEmitter = require('events').EventEmitter;

  /*
  # Manages connection to a database
  # @param {String} adapater_name
  # @param {Object} settings
  */


  DBConnection = (function(_super) {

    __extends(DBConnection, _super);

    function DBConnection(adapter_name, settings) {
      var initialize,
        _this = this;
      this.connected = false;
      initialize = require(__dirname + '/adapters/' + adapter_name);
      initialize(this, settings, function(error, adapter) {
        if (error) {
          _this.emit('error', error);
          return;
        }
        _this._adapter = adapter;
        _this.connected = true;
        return _this.emit('connected');
      });
    }

    return DBConnection;

  })(EventEmitter);

  module.exports = DBConnection;

}).call(this);
