// Generated by CoffeeScript 1.7.1
(function() {
  var Promise;

  Promise = require('bluebird');

  exports.execute = function(callback, func) {
    return Promise.promisify(func)().nodeify(callback);
  };

}).call(this);
