// Generated by CoffeeScript 1.4.0
(function() {
  var _plural_rules, _uncountable_words;

  _plural_rules = [['person$', 'people'], ['man$', 'men'], ['s$', 's'], ['$', 's']];

  _uncountable_words = ['fish', 'money', 'rice', 'sheep'];

  exports.foreign_key = function(name) {
    return exports.underscore(name) + '_id';
  };

  exports.pluralize = function(str) {
    var rule, _i, _len;
    if (_uncountable_words.indexOf(str.toLowerCase()) === -1) {
      for (_i = 0, _len = _plural_rules.length; _i < _len; _i++) {
        rule = _plural_rules[_i];
        if (!(rule[0] instanceof RegExp)) {
          rule[0] = new RegExp(rule[0], 'i');
        }
        if (rule[0].test(str)) {
          return str.replace(rule[0], rule[1]);
        }
      }
    }
    return str;
  };

  exports.tableize = function(name) {
    return exports.pluralize(exports.underscore(name));
  };

  exports.underscore = function(str) {
    str = str.replace(/([A-Z0-9]+)([A-Z][a-z])/g, "$1_$2");
    str = str.replace(/([a-z0-9])([A-Z])/g, "$1_$2");
    str = str.replace('-', '_');
    str = str.toLowerCase();
    return str;
  };

}).call(this);
