// Generated by CoffeeScript 1.3.3
(function() {
  var DBModel;

  DBModel = (function() {

    function DBModel() {}

    DBModel.prototype.save = function(callback) {
      var ctor,
        _this = this;
      if (this.id) {

      } else {
        ctor = this.constructor;
        return ctor._connection._adapter.create(ctor._name, this, function(error, id) {
          if (!error) {
            _this.id = id;
          }
          return callback(error);
        });
      }
    };

    DBModel.drop = function(callback) {
      return this._connection._adapter.drop(this._name, callback);
    };

    DBModel.deleteAll = function(callback) {
      return this._connection._adapter.deleteAll(this._name, callback);
    };

    return DBModel;

  })();

  module.exports = DBModel;

}).call(this);
