// Generated by CoffeeScript 1.6.2
(function() {
  var Query, async, _, _bindDomain;

  _ = require('underscore');

  async = require('async');

  _bindDomain = function(fn) {
    var d;

    if (d = process.domain) {
      return d.bind(fn);
    } else {
      return fn;
    }
  };

  Query = (function() {
    function Query(model) {
      this._model = model;
      this._name = model._name;
      this._connection = model._connection;
      this._adapter = model._connection._adapter;
      this._conditions = [];
      this._options = {
        orders: []
      };
    }

    Query.prototype.find = function(id) {
      if (Array.isArray(id)) {
        this._id = _.uniq(id);
        this._find_single_id = false;
      } else {
        this._id = id;
        this._find_single_id = true;
      }
      return this;
    };

    Query.prototype.findPreserve = function(ids) {
      this._id = _.uniq(ids);
      this._find_single_id = false;
      this._preserve_order_ids = ids;
      return this;
    };

    Query.prototype.near = function(target) {
      this._options.near = target;
      return this;
    };

    Query.prototype.where = function(condition) {
      if (Array.isArray(condition)) {
        this._conditions.push.apply(this._conditions, condition);
      } else if (condition != null) {
        this._conditions.push(condition);
      }
      return this;
    };

    Query.prototype.select = function(columns) {
      var schema_columns, select;

      this._options.select = null;
      schema_columns = Object.keys(this._model._schema);
      if (typeof columns === 'string') {
        select = [];
        columns.split(/\s+/).forEach(function(column) {
          if (schema_columns.indexOf(column) >= 0) {
            return select.push(column);
          } else {
            column += '.';
            return schema_columns.forEach(function(sc) {
              if (sc.indexOf(column) === 0) {
                return select.push(sc);
              }
            });
          }
        });
        this._options.select = select;
      }
      return this;
    };

    Query.prototype.order = function(orders) {
      var schema_columns,
        _this = this;

      schema_columns = Object.keys(this._model._schema);
      if (typeof orders === 'string') {
        orders.split(/\s+/).forEach(function(order) {
          var asc;

          asc = true;
          if (order[0] === '-') {
            asc = false;
            order = order.slice(1);
          }
          if (schema_columns.indexOf(order) >= 0) {
            return _this._options.orders.push(asc ? order : '-' + order);
          }
        });
      }
      return this;
    };

    Query.prototype.group = function(group_by, fields) {
      var columns, schema_columns;

      this._options.group_by = null;
      schema_columns = Object.keys(this._model._schema);
      if (typeof group_by === 'string') {
        columns = group_by.split(/\s+/).filter(function(column) {
          return schema_columns.indexOf(column) >= 0;
        });
        this._options.group_by = columns;
      }
      this._options.group_fields = fields;
      return this;
    };

    Query.prototype.limit = function(limit) {
      this._options.limit = limit;
      return this;
    };

    Query.prototype.exec = function(options, callback) {
      var expected_count,
        _this = this;

      if (this._model._waitingForReady(this, this.exec, arguments)) {
        return;
      }
      if (typeof options === 'function') {
        callback = options;
        options = {};
      }
      if (this._find_single_id && this._conditions.length === 0) {
        if (!(options != null ? options.skip_log : void 0)) {
          this._connection.log(this._name, 'find by id', {
            id: this._id,
            options: this._options
          });
        }
        this._adapter.findById(this._name, this._id, this._options, _bindDomain(function(error, record) {
          if (error || !record) {
            return callback(new Error('not found'));
          }
          return callback(null, record);
        }));
        return;
      }
      expected_count = void 0;
      if (this._id) {
        if (Array.isArray(this._id)) {
          if (this._id.length === 0) {
            return callback(null, []);
          }
          this._conditions.push({
            id: {
              $in: this._id
            }
          });
          expected_count = this._id.length;
        } else {
          this._conditions.push({
            id: this._id
          });
          expected_count = 1;
        }
      }
      if (!(options != null ? options.skip_log : void 0)) {
        this._connection.log(this._name, 'find', {
          conditions: this._conditions,
          options: this._options
        });
      }
      return this._adapter.find(this._name, this._conditions, this._options, _bindDomain(function(error, records) {
        if (error) {
          return callback(error);
        }
        if (expected_count != null) {
          if (records.length !== expected_count) {
            return callback(new Error('not found'));
          }
        }
        if (_this._preserve_order_ids) {
          return callback(null, _this._preserve_order_ids.map(function(id) {
            var record, _i, _len;

            for (_i = 0, _len = records.length; _i < _len; _i++) {
              record = records[_i];
              if (record.id === id) {
                return record;
              }
            }
          }));
        } else {
          return callback(null, records);
        }
      }));
    };

    Query.prototype.count = function(callback) {
      if (this._model._waitingForReady(this, this.count, arguments)) {
        return;
      }
      if (this._id) {
        this._conditions.push({
          id: this._id
        });
        delete this._id;
      }
      this._connection.log(this._name, 'count', {
        conditions: this._conditions
      });
      return this._adapter.count(this._name, this._conditions, _bindDomain(callback));
    };

    Query.prototype._validateAndBuildSaveData = function(errors, data, updates, path, object) {
      var column, error, model, property, schema, _results;

      model = this._model;
      schema = model._schema;
      _results = [];
      for (column in object) {
        property = schema[path + column];
        if (property) {
          try {
            model._validateColumn(updates, path + column, property);
          } catch (_error) {
            error = _error;
            errors.push(error);
          }
          _results.push(model._buildSaveDataColumn(data, updates, path + column, property, true));
        } else if (typeof object[column] === 'object') {
          _results.push(this._validateAndBuildSaveData(errors, data, updates, path + column + '.', object[column]));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Query.prototype.update = function(updates, callback) {
      var data, errors;

      if (this._model._waitingForReady(this, this.update, arguments)) {
        return;
      }
      errors = [];
      data = {};
      this._validateAndBuildSaveData(errors, data, updates, '', updates);
      if (errors.length > 0) {
        return callback(new Error(errors.join(',')));
      }
      if (this._id) {
        this._conditions.push({
          id: this._id
        });
        delete this._id;
      }
      this._connection.log(this._name, 'update', {
        data: data,
        conditions: this._conditions,
        options: this._options
      });
      return this._adapter.updatePartial(this._name, data, this._conditions, this._options, _bindDomain(callback));
    };

    Query.prototype._doIntegrityActions = function(integrities, ids, callback) {
      var _this = this;

      return async.forEach(integrities, function(integrity, callback) {
        var conditions, data;

        if (integrity.type === 'parent_nullify') {
          data = {};
          data[integrity.column] = null;
          conditions = {};
          conditions[integrity.column] = ids;
          return integrity.child.update(data, conditions, function(error, count) {
            return callback(error);
          });
        } else if (integrity.type === 'parent_restrict') {
          conditions = {};
          conditions[integrity.column] = ids;
          return integrity.child.count(conditions, function(error, count) {
            if (error) {
              return callback(error);
            }
            if (count > 0) {
              return callback(new Error('rejected'));
            }
            return callback(null);
          });
        } else if (integrity.type === 'parent_delete') {
          conditions = {};
          conditions[integrity.column] = ids;
          return integrity.child["delete"](conditions, function(error, count) {
            if (error) {
              return callback(error);
            }
            return callback(null);
          });
        } else {
          return callback(null);
        }
      }, callback);
    };

    Query.prototype._doArchiveAndIntegrity = function(options, callback) {
      var integrities, need_archive, need_child_archive, need_integrity,
        _this = this;

      need_archive = this._model.archive;
      integrities = this._model._integrities.filter(function(integrity) {
        return integrity.type.substr(0, 7) === 'parent_';
      });
      need_child_archive = integrities.some(function(integrity) {
        return integrity.child.archive;
      });
      need_integrity = need_child_archive || (integrities.length > 0 && !this._adapter.native_integrity);
      if (!need_archive && !need_integrity) {
        return callback(null);
      }
      return async.waterfall([
        function(callback) {
          var query;

          query = _this._model.where(_this._conditions);
          if (!need_archive) {
            query.select('');
          }
          return query.exec({
            skip_log: options != null ? options.skip_log : void 0
          }, callback);
        }, function(records, callback) {
          var archive_records;

          if (!need_archive) {
            return callback(null, records);
          }
          archive_records = records.map(function(record) {
            return {
              model: _this._name,
              data: record
            };
          });
          return _this._connection.models['_Archive'].createBulk(archive_records, function(error) {
            if (error) {
              return callback(error);
            }
            return callback(null, records);
          });
        }, function(records, callback) {
          var ids;

          if (!need_integrity) {
            return callback(null);
          }
          if (records.length === 0) {
            return callback(null);
          }
          ids = records.map(function(record) {
            return record.id;
          });
          return _this._doIntegrityActions(integrities, ids, callback);
        }
      ], callback);
    };

    Query.prototype["delete"] = function(options, callback) {
      var _this = this;

      if (this._model._waitingForReady(this, this["delete"], arguments)) {
        return;
      }
      if (typeof options === 'function') {
        callback = options;
        options = {};
      }
      if (this._id) {
        this._conditions.push({
          id: this._id
        });
        delete this._id;
      }
      if (!(options != null ? options.skip_log : void 0)) {
        this._connection.log(this._name, 'delete', {
          conditions: this._conditions
        });
      }
      return this._doArchiveAndIntegrity(options, function(error) {
        if (error) {
          return callback(error);
        }
        return _this._adapter["delete"](_this._name, _this._conditions, _bindDomain(callback));
      });
    };

    return Query;

  })();

  module.exports = Query;

}).call(this);
