// Generated by CoffeeScript 1.4.0
(function() {
  var Integer, RecordID;

  exports.String = 'string';

  exports.Number = 'number';

  exports.Boolean = 'boolean';

  exports.Integer = 'integer';

  exports.GeoPoint = 'geopoint';

  exports.Date = 'date';

  exports.Object = 'object';

  RecordID = (function() {

    function RecordID() {}

    return RecordID;

  })();

  Integer = (function() {

    function Integer() {}

    return Integer;

  })();

}).call(this);
