name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_DATABASE: cormo_test
          MYSQL_USER: cormo_test
          MYSQL_PASSWORD: cormo_test
        ports:
          - 21860:3306
      mongo:
        image: mongo:3.6-jessie
        ports:
          - 21861:27017
      postgres:
        image: croquiscom/postgis-pgvector:16-3.5-0.7.3
        env:
          POSTGRES_DB: cormo_test
          POSTGRES_USER: cormo_test
          POSTGRES_PASSWORD: cormo_test
        ports:
          - 21862:5432
      redis:
        image: redis:4-alpine
        ports:
          - 21863:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install packages
        run: |
          npm install
          (cd packages/cormo ; npm install)
          (cd packages/graphql ; npm install)

      - name: Run test
        run: |
          (cd packages/cormo ; npm run test:cov)
          (cd packages/graphql ; npm run test:cov)

      - name: Check file changes
        run: |
          (cd packages/cormo ; npm run build)
          (cd packages/graphql ; npm run build)
          npx prettier --version
          npx prettier --check . || exit 100
          git status --short
          git diff
          git diff --quiet

      - name: Coveralls
        uses: coverallsapp/github-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
